baseurl                 = "/"
relativeURLs            = true
languageCode            = "en-us"
defaultContentLanguage  = "en"
isMultilingual          = false
title                   = "PhDnet Winter Social - Open Science Escape Room"
theme                   = "sam"
pygmentsStyle           = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
publishDir              = "docs"
googleAnalytics         = "G-0CS8JKDMHZ"

[markup.goldmark.renderer]
      unsafe = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "images/MaxPlanckPhDnet_logo_square_FINAL.jpg"
    homepage            = "home"                           # What to call the home page link
    footerText          = ""
  #  companylogo         = "images/MaxPlanckPhDnet_logo_square_FINAL.jpg"
    companylogo         = "images/PhDnet_OS_logo.jpg"
    logoheight          = "80px"
    companysite         = "https://www.phdnet.mpg.de/home"

# Metadata for Open Graph and Twitter
    description         = "Interactive site for the Escape Room at the Max Planck PhDnet Winter Social 2020"
    images              = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title               = "Open Science Escape Room"
    # rss               = ""

[[params.videoBackground.sources]]
    #source  = "images/background_video.mp4"
    source  = "images/Christmas_EscapeRoom.mp4"
    type    = "video/mp4"
  #  poster  = "images/background.jpg"
    poster  = "images/PhdNet_WinterSocial.jpg"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.6)" # optional

#[[params.mainMenu]]
#    link = "pages/program"
#    text = "program"
#[[params.mainMenu]]
#    link = "/items/closed"
#    text = "THE ESCAPE ROOM IS CLOSED"
[[params.mainMenu]]
    link = "instructions"
    text = "instructions"
[[params.mainMenu]]
    link = "introduction"
    text = "start"
[[params.mainMenu]]
    link = "tasks"
    text = "tasks"
[[params.mainMenu]]
    link = "about"
    text = "about"

[imaging]
    quality = 75
